name: Generate Contribution Snake

on:
  push:
    branches:
      - main  # Adjust as per your branch name

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
        # Output to root directory
        env:
          OUTPUT_FILE: './github-snake.svg'

      - name: Save generated SVG
        run: mv $GITHUB_WORKSPACE/github-snake.svg .

      - name: Commit and push if changed
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add github-snake.svg
          git commit -m "Generated GitHub snake graph"
          git push

